# Generated by Django 3.1.7 on 2023-10-06 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('quantity', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('price', models.FloatField()),
                ('invoice_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.invoice')),
            ],
        ),
    ]
